### ISSUE TITLE
Need help to find xpath of a multiselect element (Add new option in multiselect dropdown)

### ISSUE THREAD

**Issue by PantHarry-21** [webdriverio/.github#1]
Hi,
I am trying to click an option from a multiselect dropdown. The option is inside div and when clicking the option the dropdown is being closed. I am not able to get it's xpath element. 
attaching screenshot of the code block which is being closed when trying to get xpath of the option (Highlighted)

![image](https://user-images.githubusercontent.com/108737833/193260583-8502170a-ebcb-4173-bfc6-fcaeb2f72b8d.png)

Please help!

**Comment by seanpoulter** [comment]
Sorry we missed your question @PantHarry-21. This repository is used to maintain a internal templates so the Issues aren't monitored. If you're still having trouble please reach out to the [Community](https://webdriver.io/community/resources/#community) and we'd be happy to help
